### PR TITLE
Phantomjs 2.0.0

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by lfryc** [comment]
I wonder if there is a way how we could make linux binaries accessible elsewhere,
I have to read the upstream discussion first.

**Comment by MatousJobanek** [comment]
Hi,
this is corresponding PR into phantom-driver https://github.com/qa/arquillian-phantom-driver/pull/21
I've tested it but unfortunately the tests failed on Mac OS X with java 8:
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/Arquillian/job/Arquillian-phantom-driver-mjobanek/jdk=java18_default,label_exp=macosx/39/console
Do you have any idea what could be wrong?

**Comment by bobmcwhirter** [comment]
Apparently some flavors of OSX also have an issue with stock PhantomJS 2.0

See https://github.com/eugene1g/phantomjs/releases

**Comment by lfryc** [comment]
PhantomJS was announced: https://groups.google.com/forum/#!msg/phantomjs/Jp4sDXrfmNg/I5J5TBFBDQAJ

and seems all binaries are available for download: http://phantomjs.org/download.html

**Comment by lfryc** [comment]
@MatousJobanek also staged a 2.1.1 binary release here: https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-7558/

**Comment by lfryc** [comment]
Tracking testing progress here: https://github.com/qa/arquillian-phantom-driver/pull/22

**Comment by lfryc** [comment]
Oh, just noticed this is PR for 2.1.1. @MatousJobanek I believe we should close this and open a new one for 2.1.1, right?

**Comment by MatousJobanek** [comment]
Closing this PR as it is already merged. 
Discussion related to the update to PhantomJS 2.1.1 can continue here: https://github.com/qa/arquillian-phantom-driver/pull/22
and here: https://github.com/qa/arquillian-phantom-driver/pull/22

**Pull request closed without merging**
